# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

# source 'https://github.com/CocoaPods/Specs.git'
# source 'https://github.com/zhangao0086/DKImagePickerController.git'
# pod 'DKImagePickerController'
# source 'https://github.com/CocoaPods/Specs.git'
# source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
# source 'https://github.com/CocoaPods/Specs.git'
# pod 'FBSDKCoreKit'
# FBSDKCoreKit (15.1.0)
# pod 'FBSDKCoreKit', '~> 15.1.0'
#     pod 'Firebase/Core'

#    pod 'ENSwiftSideMenu', :git => 'https://github.com/evnaz/ENSwiftSideMenu.git', :branch => 'master'



def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#     flutter_additional_ios_build_settings(target)
#   end
# end

post_install do |installer|
  installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
#                 config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'No'
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
             end
        end
 end

    installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
  #避免macos 15的问题BoringSSL-GRPC unsupported option '-G' for target 'arm64-apple-ios15.0'
      installer.pods_project.targets.each do |target|
          if target.name == 'BoringSSL-GRPC'
            target.source_build_phase.files.each do |file|
              if file.settings && file.settings['COMPILER_FLAGS']
                flags = file.settings['COMPILER_FLAGS'].split
                flags.reject! { |flag| flag == '-GCC_WARN_INHIBIT_ALL_WARNINGS' }
                file.settings['COMPILER_FLAGS'] = flags.join(' ')
              end
            end
          end
        end
end

# post_install do |installer|
# #     installer.generated_projects.each do |project|
# #           project.targets.each do |target|
# #               target.build_configurations.each do |config|
# #                   config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
# #                end
# #           end
# #    end
#    installer.pods_project.targets.each do |target|
#          flutter_additional_ios_build_settings(target)
#    end
# end


# post_install do |installer|
#     installer.pods_project.targets.each do |target|
#         target.build_configurations.each do |config|
#             config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
#         end
#     end
# end

# source 'https://github.com/CocoaPods/Specs.git'
# source 'https://github.com/aliyun/aliyun-specs.git'
# pod 'AlicloudPush', '~> 1.9.1'
# source 'https://github.com/aliyun/aliyun-specs.git'
# pod 'AlicloudPush', '~> 1.9.1'
#lzb 我加的 否则找不到FMDB framework 所以认为加上去了
pod 'FMDB', '~> 2.7.12'
pod 'Toast', '~> 4.0.0'
pod 'nanopb'

# pod 'FirebaseAnalytics', '~> 11.7.0'

# pod 'sqflite_darwin', '~> 0.0.4'

# pod 'sqflite', ''
# pod 'open_file', '~> 1.0.0'
# pod 'file_selector_ios', '~> 0.0.1'
